export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  content: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "how-to-calculate-tiktok-shop-profit",
    title: "How to Calculate TikTok Shop Profit",
    description:
      "Learn how to calculate TikTok Shop profit after product costs, platform fees, affiliate commissions and advertising expenses.",
    publishedAt: "2026-08-18",
    content: [
      "TikTok Shop revenue is not the same as profit. Sellers need to account for product costs, platform fees, shipping, affiliate commissions and advertising expenses.",
      "A simple profit formula is: Selling Price minus Product Cost, Shipping Cost, Platform Fees, Affiliate Commission and Advertising Cost.",
      "For example, if a product sells for $40 and the total costs are $28, the estimated profit is $12.",
      "Use the SellerCalc AI TikTok Shop Profit Calculator to estimate your margin before launching or scaling a product.",
    ],
  },
  {
    slug: "tiktok-shop-fees-guide",
    title: "TikTok Shop Fees Explained",
    description:
      "A practical guide to the different costs TikTok Shop sellers should consider when pricing products.",
    publishedAt: "2026-08-18",
    content: [
      "TikTok Shop sellers need to consider several costs when calculating product profitability.",
      "Depending on the market, product category and seller configuration, applicable platform charges can vary.",
      "Instead of relying on a single percentage, sellers should calculate their complete cost structure before setting a selling price.",
      "SellerCalc AI provides a simple fee calculator to help sellers estimate these costs.",
    ],
  },
  {
    slug: "tiktok-shop-roas-guide",
    title: "What Is a Good TikTok Shop ROAS?",
    description:
      "Understand ROAS and why a high ROAS does not always mean a profitable TikTok Shop product.",
    publishedAt: "2026-08-18",
    content: [
      "ROAS stands for Return on Advertising Spend.",
      "The basic formula is revenue generated by advertising divided by advertising spend.",
      "A 3x ROAS means that every $1 spent on advertising generated $3 in attributed revenue.",
      "However, ROAS alone does not determine profitability. Product cost, marketplace fees, affiliate commissions and other expenses also matter.",
    ],
  },
];